{{- if .Values.workloadIdentity.createKSA }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workloadIdentity.ksaName }}
  namespace: {{ .Values.workloadIdentity.ksaNamespace }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.workloadIdentity.gsaEmail | quote }}
{{- end }}
