apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  projectID: "cc-sa-sandbox-20200619"
  credentials:
    source: InjectedIdentity # common to all gcp providers
    impersonateServiceAccount:
      name: "crossplane-gsa@cc-sa-sandbox-20200619.iam.gserviceaccount.com"
    # source: AccessToken
    # secretRef:
    #   namespace: crossplane-system
    #   name: gcp-access-token
    #   key: token