{{- $namespace := .Values.kubernetes.namespace -}}
{{- $projectID := .Values.gsm.projectId -}}
{{- range .Values.gsm.secrets }}
{{ with $sm := . }}
apiVersion: secretmanager.gcp.upbound.io/v1beta2
kind: Secret
metadata:
  name: {{ $sm.name }}
  namespace: {{ $namespace }}
spec:
  forProvider:
    project: {{ $projectID }}
    replication:
      userManaged:
        replicas:
          - location: {{ $sm.region }}
{{- end }}
{{- end }}