{{- $namespace := .Values.kubernetes.namespace -}}
{{- $prefix := .Values.application.name }}
{{- $projectID := .Values.gcp.project_id -}}
{{- range $sqlInstances := .Values.cloudsql }}
{{- range $user := $sqlInstances.users }}
---
apiVersion: secretmanager.gcp.upbound.io/v1beta2
kind: Secret
metadata:
  name: {{ $prefix }}-{{ $sqlInstances.name }}-{{ $user.name }}-password
  namespace: {{ $namespace }}
spec:
  forProvider:
    project: {{ $projectID }}
    replication:
      userManaged:
        replicas:
          - location: {{ $.Values.gsm.region }}
{{- end }}
{{- end }}