{{- $namespace := .Release.Namespace -}}
{{- $projectID := .Values.gcp.project_id -}}
{{- range .Values.gcp.secretmanager }}
{{ with $sm := . }}
apiVersion: secretmanager.gcp.upbound.io/v1beta2
kind: Secret
metadata:
  name: {{ $sm.name }}
  namespace: {{ $namespace }}
spec:
  forProvider:
    project: {{ $sm.project_id }}
    replication:
      userManaged:
        replicas:
          - location: asia-southeast1
{{- end }}
{{- end }}