{{- $prefix := .Values.application.name }}
{{- $namespace := .Values.kubernetes.namespace -}}
{{- $projectID := .Values.gcp.project_id -}}
{{- $gsm := .Values.gsm -}}
{{- range .Values.cloudsql }}
{{with $sqlInstance := . }}
---
apiVersion: sql.gcp.upbound.io/v1beta1
kind: DatabaseInstance
metadata:
  name: {{ $prefix }}-{{ $sqlInstance.name }}
spec:
  forProvider:
    project: {{ $projectID }}
    databaseVersion: {{ $sqlInstance.database_version }}
    region: {{ $sqlInstance.region }}
    settings:
      - tier: {{ $sqlInstance.tier }}
        edition: {{ $sqlInstance.edition }}
        availabilityType: {{ $sqlInstance.availability_type }}
        diskSize: {{ $sqlInstance.disk_size }}
        diskAutoresize: {{ $sqlInstance.disk_autoresize }}
        deletionProtectionEnabled: false
        databaseFlags: 
        {{- toYaml $sqlInstance.databaseFlags | nindent 10 }}
        ipConfiguration:
          - ipv4Enabled: {{ $sqlInstance.ipConfiguration.ipv4Enabled | default false }}
            privateNetwork: {{ $sqlInstance.ipConfiguration.privateNetwork | default "" }}
  writeConnectionSecretToRef:
    name: {{ $prefix }}-{{ $sqlInstance.name }}-conn
    namespace: {{ $namespace }}
{{- end }}
{{- end }}