{{- $namespace := .Values.kubernetes.namespace -}}
{{- $prefix := .Values.application.name }}
{{- $projectID := .Values.gsm.projectId -}}
{{- range $sqlInstances := .Values.cloudsql }}
{{ with $sqlInstance := . }}
---
apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: SecretVersion
metadata:
  name: {{ $prefix }}-{{ $sqlInstance.name }}-host
spec:
  forProvider:
    secretDataSecretRef:
      name: {{ $prefix }}-{{ $sqlInstance.name }}-conn
      key: {{ if $sqlInstance.ipConfiguration.privateNetwork }}privateIP{{ else }}publicIP{{ end }}
      namespace: {{ $namespace }}
    secretRef:
      name: {{ $prefix }}-{{ $sqlInstance.name }}-host
---
{{- range $user := $sqlInstance.users }}
{{/* write password for $user to secret version */}}
apiVersion: secretmanager.gcp.upbound.io/v1beta1
kind: SecretVersion
metadata:
  name: {{ $prefix }}-{{ $sqlInstance.name }}-{{ $user.name }}-password
spec:
  forProvider:
    secretDataSecretRef:
      name: {{ $prefix }}-{{ $sqlInstance.name }}-{{ $user.name }}-password
      key: password
      namespace: {{ $namespace }}
    secretRef:
      name: {{ $prefix }}-{{ $sqlInstance.name }}-{{ $user.name }}-password
{{- end }}
{{- end }}
{{- end }}