{{- $projectID := .Values.gcp.projectId -}}
{{- $prefix := .Values.application.name }}
{{- range $sqlInstances := .Values.cloudsql }}
{{- range $database := $sqlInstances.databases }}
{{ with $sqlInstance := . }}
---
apiVersion: sql.gcp.upbound.io/v1beta1  
kind: Database
metadata:
  name: {{ $database.name }}
spec:
  forProvider:
    charset: {{ $database.charset }}
    instanceRef:
      name: {{ $prefix }}-{{ $sqlInstance.name }}
{{- end }}
{{- end }}
{{- end }}