kubernetes:
  namespace: default


application:
  group: test
  runtime: golang
  name: test-app-v1

gcp:
  projectId: cc-sa-sandbox-20200619
  region: asia-southeast1

  gsm_project_id: cc-sa-sandbox-20200619

cloudsql:
  - name: cloudsql-1
    region: asia-southeast1
    database_version: POSTGRES_17
    edition: ENTERPRISE
    tier: db-custom-2-8192
    diskSize: 20
    availabilityType: ZONAL
    diskAutoresize: true
    ipConfiguration:
      privateNetwork: projects/cc-sa-sandbox-20200619/global/networks/default
      ipv4Enabled: false
    databases:
      - name: test-db
        charset: UTF8
    databaseFlags:
      - name: cloudsql.iam_authentication
        value: "on"
      - name: timezone
        value: "UTC+7"
    users:
      - name: dbuser
      - name: dbuser2
      
    # - name: cloudsql-2
    #   region: asia-southeast1
    #   edition: ENTERPRISE
    #   database_version: POSTGRES_17
    #   tier: db-custom-2-8192
    #   disk_size: 20


gsm:
  projectId: cc-sa-sandbox-20200619
  region: asia-southeast1
  secrets:
    - name: test-app-v1-cloudsql-1-host
    - name: test-app-v1-cloudsql-1-password
