kubernetes:
  namespace: default


application:
  group: test
  runtime: golang
  name: test-app-v2

gcp:
  projectId: cc-sa-sandbox-20200619
  region: asia-southeast1

cloudsql:
  - name: cloudsql-1
    region: asia-southeast1
    databaseVersion: POSTGRES_17
    edition: ENTERPRISE
    tier: db-custom-2-8192
    diskSize: 20
    availabilityType: ZONAL
    diskAutoresize: true
    deletionProtection: false
    ipConfiguration:
      privateNetwork: projects/cc-sa-sandbox-20200619/global/networks/default
      ipv4Enabled: true
    # backup configuration
    backupConfiguration:
      enabled: true
      backupRetentionSettings:
        retainedBackups: 7
      # PIT recovery configuration: valid only for PostgreSQL and MSSQL
      pointInTimeRecoveryEnabled: true
      location: asia-southeast1
      backupRetentionUnit: DAY
      backupStartTime: "00:00"
    databases:
      - name: default
        charset: UTF8
    databaseFlags:
      - name: cloudsql.iam_authentication
        value: "on"
      - name: timezone
        value: "UTC+7"
      - name: cloudsql.enable_pgaudit
        value: "on"
      - name: pgaudit.log
        value: 'all'
    users:
      - name: dbuser1
  #     - name: dbuser2
  # - name: cloudsql-2
  #   region: asia-southeast1
  #   databaseVersion: MYSQL_8_4
  #   edition: ENTERPRISE
  #   tier: db-custom-2-8192
  #   diskSize: 20
  #   availabilityType: ZONAL
  #   diskAutoresize: true
  #   ipConfiguration:
  #     privateNetwork: projects/cc-sa-sandbox-20200619/global/networks/default
  #     ipv4Enabled: true
  #   databases:
  #     - name: test-db
  #       charset: UTF8
  #   users:
  #     - name: dbuser3
  #       host: "%"
  #     - name: dbuser4
  #       host: "%"
      
    # - name: cloudsql-2
    #   region: asia-southeast1
    #   edition: ENTERPRISE
    #   database_version: POSTGRES_17
    #   tier: db-custom-2-8192
    #   disk_size: 20


gsm:
  project: cc-sa-sandbox-20200619
  region: asia-southeast1
