{{- $namespace := .Values.kubernetes.namespace -}}
{{- $prefix := .Values.application.name }}
{{- $projectID := .Values.gsm.project -}}
{{- range $sqlInstances := .Values.cloudsql }}
{{ with $sqlInstance := . }}
apiVersion: secretmanager.gcp.upbound.io/v1beta2
kind: Secret
metadata:
  name: {{ $prefix }}-{{ $sqlInstance.name }}-host
spec:
  forProvider:
    project: {{ $projectID }}
    replication:
      userManaged:
        replicas:
          - location: {{ $.Values.gsm.region }}
{{- end }}
{{- end }}