{{/* NOTE: TESTING PURPOSES ONLY, DO NOT USE IN PRODUCTION */}}
{{- $prefix := .Values.application.name }}
{{- $projectID := .Values.gsm.project -}}
{{- range $sqlInstances := .Values.cloudsql }}
---
apiVersion: secretmanager.gcp.upbound.io/v1beta2
kind: Secret
metadata:
  name: {{ $prefix }}-{{ $sqlInstances.name }}-root-password
spec:
  forProvider:
    project: {{ $projectID }}
    replication:
      userManaged:
        replicas:
          - location: {{ $.Values.gsm.region }}
{{- end }}