{{/* TODO: Confirm with Ajaib team if this is the expected way to generate random password */}}

{{- $namespace := .Values.kubernetes.namespace -}}
{{- $prefix := .Values.application.name }}
{{- $projectID := .Values.gcp.project_id -}}
{{- range $sqlInstances := .Values.cloudsql }}
{{ with $sqlInstance := . }}
{{- range $user := $sqlInstance.users }}
---
apiVersion: sql.gcp.upbound.io/v1beta1
kind: User
metadata:
  name: {{ $user.name }}
spec:
  forProvider:
    passwordSecretRef:
      name: {{ $prefix }}-{{ $sqlInstance.name }}-{{ $user.name }}-password
      key: password
      namespace: {{ $namespace }}
    {{- if contains "mysql" (lower $sqlInstance.databaseVersion) }}
    host: {{ $user.host | default "%" | quote }}
    {{- end }}
    instanceRef:
      name: {{ $prefix }}-{{ $sqlInstance.name }}
{{- end }}
{{- end }}
{{- end }}